import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

import { Providers } from "#/app/providers";
import { Footer, Header } from "#/components";

export const metadata: Metadata = {
  title: "BEST Erlangen - AI Hackathon 2024",
  description: "Generated by Enigma Team.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
